services:
  auditlog-api:
    image: auditlog-api
    container_name: auditlog-api
    build:
      context: .
      dockerfile: AuditLog.Application/AuditLog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5630:8080"
    depends_on:
      auditlog-db:
        condition: service_healthy

  auditlog-ui:
    build:
      context: ./AuditLog.Ui
      dockerfile: Dockerfile
    image: auditlog-ui
    container_name: auditlog-ui
    ports:
      - "8630:80"

  auditlog-db:
    container_name: auditlog-db
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./AuditLog.Database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s